baseURL = 'https://0x-mdk.github.io/'
languageCode = 'en-us'
title = '0x-MDK'
theme="PaperMod"

[params.profileMode]
enabled = true
title = "<Title>"
subtitle = "CyberSecurity Student @ ULB"
imageUrl = "images/pfp.jpeg"
imageTitle = "Logo"
imageWidth = 140
imageHeight = 150

  [[params.profileMode.buttons]]
  name = "Github"
  url = "https://github.com/"

[[params.socialIcons]]
name = "github"
url = "https://github.com/0x-mdk"


