baseURL = 'https://meddak-be.github.io/'
languageCode = 'en-us'
title = 'meddak'
theme="PaperMod"

[params.profileMode]
enabled = true
title = "<Title>"
subtitle = "CyberSecurity Student @ ULB"
imageUrl = "images/pfp.jpeg"
imageTitle = "Logo"
imageWidth = 200
imageHeight = 210

  [[params.profileMode.buttons]]
  name = "Github"
  url = "https://github.com/"

[[params.socialIcons]]
name = "github"
url = "https://github.com/meddak-be"


