baseURL = 'https://meddak-be.github.io/'
languageCode = 'en-us'
title = 'meddak'
theme="PaperMod"

[params.profileMode]
enabled = true
title = "Eddak M. Said"
subtitle = "CyberSecurity Student @ ULB"
imageUrl = "images/pfp.jpeg"
imageTitle = "Logo"
imageWidth = 250
imageHeight = 250


[[params.socialIcons]]
name = "github"
url = "https://github.com/meddak-be"

[[params.socialIcons]]
name = "linkedin-in"
url = "https://www.linkedin.com/in/mohammed-eddak-2518aa23b/"

[[params.socialIcons]]
name = "medium-m"
url = "https://medium.com/@MDK_BE"


[menu]
  [[menu.main]]
    identifier = "posts"
    name = "Posts"
    url = "/posts/"